### ISSUE TITLE
npm version spec needed

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1080]
When using an import statement like: import "@openzeppelin/contracts/token//ERC20/ERC20.sol”; do we have a way of specifying the version? Via github we do - but via NPM only the latest is accessable?

**Comment by cameel** [comment]
Technically, `solc` supports that via import remapping ([Layout of a Solidity Source File > Use in Actual Compilers](https://docs.soliditylang.org/en/latest/layout-of-source-files.html#use-in-actual-compilers)), but I don't think Remix IDE exposes remappings to the user in any way.

I'd be interested to hear if remappings are actually a viable option for something like this because we've been discussing potentially removing or at least simplifying them in the compiler.

**Comment by ryestew** [comment]
This import statement now works in Remix:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts@4.1.0/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {
    constructor() ERC20("MyToken", "MTK") {}
}
```

so we can close this issue
