### ISSUE TITLE
Downloading the source code creates zip with no contents

### ISSUE THREAD

**Issue by aaronduchateau** [ethereum/remix-project#1118]
When i go to download the actual folder structure of the project (without flattening), I get an empty zip file. Bug, or Please advise?

**Comment by bunsenstraat** [comment]
There may be a hidden folder in the zip called ‘.workspaces’ — but you can ignore it. (On MacOS, you may not even see the .workspaces folder because directories that begin with a ‘.’ are often hidden)
If you don’t see any files, you may already cleared your browser’s local storage or you may just not have any files.

**Comment by yann300** [comment]
closing cause we already checked that I think.
@aaronduchateau please reopen if needed
