### ISSUE TITLE
View code in remix

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1853]
Something like this can be implemented with remix: https://github.com/dethcrypto/ethereum-code-viewer

User can change the etherscan URL to view deployed contract and github URL to view current file in github in Remix IDE.

cc: @yann300

**Comment by yann300** [comment]
@Aniket-Engg we already have this https://github.com/ethereum/remix-project/blob/0a06ddb3c4b94a9962a31b29e90fdde0c1bd85b9/libs/remix-core-plugin/src/lib/helpers/fetch-etherscan.ts#L1
so this shouldn't be complicated to plug this in the initWorkspace section.
The issue here is that this require the user to have fill in its etherscan key before hand.
