### ISSUE TITLE
Broken compiler list: Only one compiler available

### ISSUE THREAD

**Issue by CrapFX** [ethereum/remix-project#1882]
i cant change my compiler version, i want 0.6.12 but when i press the drop down it only gives me 0.8.7

![deletelater](https://user-images.githubusercontent.com/94172917/148230547-d8f4511e-ac10-4db8-b094-2824d1c33015.PNG)

**Comment by xaarth** [comment]
same here

**Comment by wi2xner** [comment]
same problem

**Comment by cameel** [comment]
This was caused by the issue with DNS entry for `soliditylang.org` domain. `binaries.soliditylang.org` was not reachable and Remix could not fetch the compiler list or download compiler binaries. The problem has been fixed earlier today but DNS changes might take some time to propagate.

If anyone is still facing this, a workaround is to use the [option for adding a custom compiler binary](https://remix-ide.readthedocs.io/en/latest/compile.html#custom-solidity-compilers) with a URL that does not go through that domain. `solc-bin.ethereum.org` was unaffected so if you want e.g. 0.6.12 you can use https://solc-bin.ethereum.org/bin/soljson-v0.6.12+commit.27d51765.js (you can find the names of all available binaries in [`list.txt` in solc-bin](https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.txt)).

By the way, I think that Remix should handle this kind of error more gracefully. If there's a problem with solc-bin, there should be a message saying just that (might also say to report it directly in the Solidity repo). Without this people think that it's a bug in Remix itself and keep reporting it here.
