### ISSUE TITLE
Display compiler license somewhere (in an about window)

### ISSUE THREAD

**Issue by axic** [ethereum/remix-project#247]
Use `solc.license()` to retrieve the text - it will be **very** long though.

Depends on https://github.com/ethereum/solc-js/pull/121.

**Comment by cameel** [comment]
To summarize [my answer from the chat](https://matrix.to/#/!vVfTacneThsGqrLLFd:gitter.im/$xc6ljctJs1M9hSs4D2EhVKYcONhKbJVF1IcQGcVkLco)

> Do you think license depends on compiler version?

The license seems to always have been some form of GPL. As to specific version - currently it's GPLv3 but I'm seeing different versions in history so it might have been a different version back when Solidity was a part of cpp-ethereum.

But if you meant the output of the `license()` function of the emscripten binary - this can and does change, though not frequently. It happens when someone fixes a typo or includes sources of some dependency that has a different license. Take a look at [the history of `license.h.in`](https://github.com/ethereum/solidity/commits/develop/cmake/templates/license.h.in) - it's the file the license text is generated from.
