### ISSUE TITLE
Infinite gas estimation for basic arithmetic

### ISSUE THREAD

**Issue by musicslayer** [ethereum/remix-project#3027]
Contract: Foo.sol
Compiler: 0.8.17+commit.8df45f5f

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.12 <0.9.0;
contract Foo {
    function foo() private pure returns (uint) {
        return 1 + 2;
    }
}
```

![GasEstimate](https://user-images.githubusercontent.com/10043091/196052051-05fa9b1a-1305-472a-b1bc-e992013823dd.png)

Remix estimates "infinite gas" for this function despite it only adding two known numbers together.
I would expect the estimation to be a bit more accurate than that...

**Comment by clauBv23** [comment]
That happens because the function is private, only have to change it to public/external, or call it in a public/external one and the gas estimation will be the expected one.

<img width="494" alt="Screenshot 2023-06-30 at 20 57 27" src="https://github.com/ethereum/remix-project/assets/26546018/db5c5aee-9210-4204-8916-01f1f3ca3204">

It looks like the private/internal functions gas calculation in `solc` is set to infinite and not changed unless it has an entry point.

**Comment by LianaHus** [comment]
the gas estimation remix receives from solc. we do not modify or calculate this.
