### ISSUE TITLE
use solidity-docgen for generating documentation

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#3239]
see https://github.com/OpenZeppelin/solidity-docgen 

The action should also probably be put in the solidity compiler.

**Comment by bunsenstraat** [comment]
There are problems using this lib:
it uses handlebar template files that are in the repo, these need to be loaded on runtime which won't fly in our webpack situation. We could put the templates in localstorage on load and rig fs to point to browserfs but then we'd point the fs to the wrong storage basically which could cause other modules to do crazy things. Pointing FS to the fs actually used by remix would be correct. But putting them in indexeddb is not an option because indexeddb is async and this lib uses sync reading for some strange reason - which is not necessary it seems. The best strategy is write our own version based on this idea. I would not put this in the project right now.

**Comment by bunsenstraat** [comment]
I can make a plugin for this. You can implement it in the solidity compiler UI somewhere.

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/pull/3267 Made plugin for it.
