### ISSUE TITLE
Deploy & Run plugin doc is not complete

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3830]
- "Deploy with Proxy"
- "Upgrade with Proxy"

should be covered

**Comment by ryestew** [comment]
These are covered
https://remix-ide.readthedocs.io/en/latest/run_proxy_contracts.html

I believe the problem is not the docuementation but just the link at the top of deploy and run to the 1st of the deploy & run doc pages and not to an index page of everything to do with the deploy & run - which is spread across 3 pages.
