### ISSUE TITLE
Solcoder / Solidity Copilot issues

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4684]
- [ ] is it Solcoder or Solidity Copilot for the documentation and for general naming purposes? (in this issue I'll just use Socoder cause its shorter to type) FYI: The switch says its Copilot and the printout says its Solcoder.
- [x] #4685
- [ ] The answer that is given to the delegate function of Ballot is not correct - but I think this is because a different workspace was loaded and thinks it is still in the old workspace with the previous active file.  
- [ ] But in another browser window (incognito) with the ai switch never turned on, when I highlighted a function and rt clicked, I first got Generate docs & Explain function - but then when I did it again I get Explain this code - but Explain this code should never appear if the AI switch is off or if it was never turned on right?  Now the answer is to do with the right function - unlike the point above.
- [x] #4686
- [x] /// only works when the switch is on - which is correct
- [ ]    ` /// write a function that returns an array with 3 elements that are from the function's parameters` is not returning anything but the into in the terminal. "Code Generation: Waiting for Solcoder answer..."
- [ ] sol-gpt issue: an odd hallucination of the copyright stuff - but that's OK - sort of...
<img width="1155" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/59a137fe-fa27-44a7-b959-8214eb296820">  
- [ ] gpt plus query is for GPT and sol-gpt is the query for Solcoder - right?
- [ ]

**Comment by STetsing** [comment]
>  is it Solcoder or Solidity Copilot for the documentation and for general naming purposes? (in this issue I'll just use Socoder cause its shorter to type) FYI: The switch says its Copilot and the printout says its Solcoder.

Solcoder is in somewhat the AI llm name and solidity copilot is the application on top. Analog to Open AI with GPTx.x and their paid API. The switch is right about saying copilot, since it activates copilot features built on top of solcoder.


> When the AI switch is off and when I right click on some code, I still get the Solcoder to work - is this because it was already downloaded? And when I only see Explain this code, I don't see Explain this function nor Generate documentation

- First, the in-browser-model doest not exist anymore. It has been replaced by an endpoint service
- second, you have to select exclusively a function to have `Explain this function` or `Generate documentation`. This function works on the function scope base
- third, I wanted to make `explain this code` work the same way such as `Explain this function` or `Generate documentation`


>The answer that is given to the delegate function of Ballot is not correct - but I think this is because a different workspace was loaded and thinks it is still in the old workspace with the previous active file.

Don't worry about the answers you have got these days. I am still experimenting with scaling the backend with various models. I will switch back to a model producing more solid results free from hallucinations. Same for other observed issues related to generated results


>  gpt plus query is for GPT and sol-gpt is the query for Solcoder - right? - right

**Comment by STetsing** [comment]
The outputs are more reliable yet
