### ISSUE TITLE
Injected Provider missing in Remix IDE on browser

### ISSUE THREAD

**Issue by happypsyduck** [ethereum/remix-project#4769]
Is it just me, or is Injected Provider missing from the Remix dropdown for environment on the browser IDE?

![remix_image](https://github.com/ethereum/remix-project/assets/53825716/534cd0fd-72b9-4bef-ba9a-9e5ad010e48d)

**Comment by ryestew** [comment]
@happypsyduck - please refresh the browser and you might need to turn off and on the browser extension for the wallet.  Please let us know if the problem persists.

**Comment by happypsyduck** [comment]
Hey @ryestew, I tried those suggestions and I still don't see Injected Provider as an option in the drop-down. Did something change recently? I'm pretty sure I saw the option even just a few days ago.

The browser I'm using is Mozilla Firefox 125.0.2, if that matters

**Comment by ryestew** [comment]
@happypsyduck - I just checked.  I found I had the same problem as you. I think this is not exactly a Remix problem - it seems to be more on the Firefox / metamask side ( or whatever you browser wallet is)

I think my Firefox browser had recently updated.  I checked my Addons in FireFox and then I checked Extensions inside of Addons - and found that there was no MetaMask extension installed.  It had been there...but maybe in this browser update, it was removed.  So I installed Metamask - and then it worked.  Fortunately I still had my 12 words key recreating my wallet.  After doing this, the **injected provider** did appear in Remix's **Environment** select box.

Thanks so much for reporting this.  I hope this helps. Please let me know.

BTW, we released Remix version 0.48 this past week which has an updates how the browser wallet loads and it allows for multiple wallets with EIP-6963.  But your issue seems to be the Browser extension side.

**Comment by happypsyduck** [comment]
Thanks @ryestew for the more information.

The issue is indeed with MetaMask. I updated from an older version of the browser extension and it is now working. I'm closing this issue now.
